name: Install Docker and Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}

      - name: Add all servers to known_hosts
        run: |
          SERVERS=${{ secrets.DEPLOY_SERVER_IP }}
          for SERVER in $(echo $SERVERS | tr "," "\n"); do
            ssh-keyscan -H $SERVER 2>/dev/null | sort -u >> ~/.ssh/known_hosts
          done

      - name: Check for code changes
        id: check_changes
        run: |
          git diff --quiet HEAD^ HEAD ./src || echo "CHANGED=true" >> $GITHUB_ENV

      - name: Upload project files if changed
        if: env.CHANGED == 'true'
        run: |
          SERVERS=${{ secrets.DEPLOY_SERVER_IP }}
          for SERVER in $(echo $SERVERS | tr "," "\n"); do
            ssh ${{ secrets.DEPLOY_USER }}@$SERVER "mkdir -p /tmp/vue-element-admin/"
            rsync -avz ./ ${{ secrets.DEPLOY_USER }}@$SERVER:/tmp/vue-element-admin/
          done

      - name: Install Docker if missing
        run: |
          SERVERS=${{ secrets.DEPLOY_SERVER_IP }}
          for SERVER in $(echo $SERVERS | tr "," "\n"); do
            ssh ${{ secrets.DEPLOY_USER }}@$SERVER "if ! command -v docker &> /dev/null; then
              curl -fsSL https://get.docker.com | sh && sudo usermod -aG docker ${{ secrets.DEPLOY_USER }};
            fi"
          done

      - name: Build and Run Docker Container
        run: |
          SERVERS=${{ secrets.DEPLOY_SERVER_IP }}
          for SERVER in $(echo $SERVERS | tr "," "\n"); do
            ssh ${{ secrets.DEPLOY_USER }}@$SERVER "
              cd /tmp/vue-element-admin && \
              if [ ! -f .docker-built ]; then
                docker build -t vue-element-admin:latest . && touch .docker-built;
              fi && \
              docker stop vue-element-admin || true && \
              docker rm vue-element-admin || true && \
              docker run -d --name vue-element-admin -p 8080:8080 vue-element-admin:latest
            "
          done